import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import { buildSpecExecutionContract } from "../spec-execution-contract";
import { compileDeterministicSpec as compileDeterministicSpecRaw } from "./deterministic-spec-compiler";

const TARGET_SPEC_PATH = path.resolve(
  process.cwd(),
  "automations/apps/portal-comercial/sections/default-section/cases/preview-001-segunta-prueba/case.spec.ts",
);

function compileDeterministicSpec(contract: Parameters<typeof compileDeterministicSpecRaw>[0]) {
  return compileDeterministicSpecRaw(contract, { targetSpecPath: TARGET_SPEC_PATH });
}

/**
 * Distinguishes FRESH (buildSpecExecutionContract run against current code +
 * the real PREVIEW-001 evidence shapes) from FROZEN (the already-persisted
 * plan.json executionContract, generated by an older builder version and
 * never retroactively rewritten). Only the FROZEN artifact is expected to
 * still show 6/7 -- see deterministic-spec-compiler.real-contract-integration.test.ts.
 * The FRESH pipeline, rebuilt from the same real plan/scenario evidence
 * shapes, must reach 7/7.
 */

const TIER1_LINK_CANDIDATE = {
  targetType: "structural",
  locatorCandidates: [{ strategy: "css", value: '[href="/requests/create/multiproduct"]', confidence: 0.85 }],
  structuralContext: { stableDirectAttributes: { href: "/requests/create/multiproduct" } },
  confidence: 0.85,
  validatedByInteraction: true,
};

const TIER1_DEPURAR_CANDIDATE = {
  targetType: "structural",
  locatorCandidates: [{ strategy: "css", value: '[aria-label="Depurar"]', confidence: 0.85 }],
  structuralContext: { stableDirectAttributes: { "aria-label": "Depurar" } },
  confidence: 0.85,
  validatedByInteraction: true,
};

const AMBIGUOUS_BUTTON_CANDIDATE = {
  targetType: "structural",
  locatorCandidates: [{ strategy: "role", value: "button", confidence: 0.85 }],
  structuralContext: {
    owner: { tag: "button" },
    semanticShape: ["span"],
    deterministicStructuralIdentity: false,
    identityAmbiguous: true,
    structuralIdentityMatchCount: 2,
  },
  confidence: 0.85,
  validatedByInteraction: true,
};

function buildFreshPlan() {
  return {
    version: "1.0",
    source: "discovery_generated",
    status: "validated",
    scenario: { source: "testrail", caseId: 1, externalId: "C1", title: "Segunta Prueba" },
    requiredData: [],
    steps: [
      { index: 1, action: "navigate" },
      { index: 2, action: "fill", target: { strategy: "text", value: "Usuario", exact: false } },
      { index: 3, action: "fill", target: { strategy: "text", value: "Contraseña", exact: false } },
      { index: 4, action: "press", value: "Enter", target: { strategy: "text", value: "role:textbox|Contraseña", exact: false } },
      { index: 5, action: "click", target: { strategy: "recorded:structural-owner", value: "Solicitud multiproducto", exact: false } },
      { index: 6, action: "fill", target: { strategy: "text", value: "Número de identificación", exact: false } },
      { index: 7, action: "click", target: { strategy: "recorded:css", value: "Número de identificación", exact: false } },
      { index: 8, action: "click", target: { strategy: "recorded:structural-owner", value: "Depurar", exact: false } },
    ],
    createdAt: new Date().toISOString(),
  } as any;
}

function buildFreshScenario() {
  return {
    title: "Segunta Prueba",
    steps: [
      { index: 1, action: "Ingresar usuario", technicalTargetRef: "role:textbox|Usuario" },
      { index: 2, action: "Ingresar contraseña", technicalTargetRef: "role:textbox|Contraseña" },
      { index: 3, action: "Presionar Enter", technicalTargetRef: "role:textbox|Contraseña" },
      { index: 4, action: "Clic en \"Solicitud multiproducto\"", technicalTargetRef: "role:link|Solicitud multiproducto", technicalTargetCandidates: [TIER1_LINK_CANDIDATE] },
      { index: 5, action: "Ingresar número de identificación" },
      { index: 6, action: "Presionar botón asociado a \"Número de identificación\"", technicalTargetCandidates: [AMBIGUOUS_BUTTON_CANDIDATE] },
      { index: 7, action: "Presionar \"Depurar\"", technicalTargetRef: "role:button|Depurar", technicalTargetCandidates: [TIER1_DEPURAR_CANDIDATE] },
    ],
  } as any;
}

test("fresh pipeline: buildSpecExecutionContract(real PREVIEW-001 shapes) -> compileDeterministicSpec = 7/7, zero unsupported", () => {
  const contract = buildSpecExecutionContract(buildFreshPlan(), buildFreshScenario());
  const requiredActionSteps = contract.steps.filter(
    (s) => s.required !== false && ["fill", "press", "click"].includes(s.operation),
  );
  assert.equal(requiredActionSteps.length, 7, "fresh contract must contain 7 required executable actions");

  const result = compileDeterministicSpec(contract);
  const actionBindings = result.bindings.filter((b) => b.runtimeMethod !== "expectPromotedVisible");

  assert.equal(result.unsupportedCapabilities.length, 0, `expected zero unsupported capabilities, got: ${JSON.stringify(result.unsupportedCapabilities)}`);
  assert.equal(actionBindings.length, 7, "fresh pipeline must represent all 7 required actions");
  assert.deepEqual(
    actionBindings.map((b) => b.scenarioStepIndex),
    [1, 2, 3, 4, 5, 6, 7],
  );

  // step4 and step7 each also carry a fresh, non-ambiguous tier-1 certified structural
  // target (TIER1_LINK_CANDIDATE / TIER1_DEPURAR_CANDIDATE) alongside their technicalTargetRef
  // -- per the jobId 25a2af2e-1ef3-4661-b156-5417c8783fe1 fix, that certified authority wins
  // over the coexisting ref (never downgraded by the recorded:* plan marker they also carry).
  const step4 = actionBindings.find((b) => b.scenarioStepIndex === 4)!;
  const step7 = actionBindings.find((b) => b.scenarioStepIndex === 7)!;
  assert.equal(step4.targetRef, 'css:[href="/requests/create/multiproduct"]');
  assert.equal(step4.runtimeResolutionRequired, undefined);
  assert.equal(step7.targetRef, 'css:[aria-label="Depurar"]');
  assert.equal(step7.runtimeResolutionRequired, undefined);

  // step6 is representable ONLY via the explicit runtime_resolution_required path,
  // delegating physical resolution to the existing runtime resolver.
  const step6 = actionBindings.find((b) => b.scenarioStepIndex === 6)!;
  assert.equal(step6.runtimeResolutionRequired, true);
  assert.match(result.source, /recordedLocatorFactory\(page, parseSerializedTechnicalTargetString\('role:button'\)/);

  // No fixed sleeps / waitForTimeout -- execution stays delegated to the existing promoted runtime.
  assert.doesNotMatch(result.source, /waitForTimeout/);
});
