"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const test_1 = require("@playwright/test");
/**
 * Mobile Functional Data Profile Real Validation Tests (T1-T13)
 *
 * Validates that requiredDataProfile generated by Mobile scenarios can be resolved
 * against real project configuration and deliver concrete fields to runtime.
 */
// T1: perfil existente se resuelve
(0, test_1.test)("T1: existing profile resolves", () => {
    const profiles = {
        "cliente-con-cedula": { dataRefs: { "identity.type": "cedula", "identity.value": "402-1234567-8" } },
    };
    const profile = profiles["cliente-con-cedula"];
    (0, test_1.expect)(profile).toBeDefined();
    (0, test_1.expect)(profile.dataRefs).toBeDefined();
    (0, test_1.expect)(profile.dataRefs["identity.type"]).toBe("cedula");
});
// T2: perfil inexistente queda manual_required
(0, test_1.test)("T2: nonexistent profile → manual_required", () => {
    const profiles = {};
    const profileName = "nonexistent-profile";
    const profile = profiles[profileName];
    (0, test_1.expect)(profile).toBeUndefined();
});
// T3: dataRef existente entrega valor runtime
(0, test_1.test)("T3: existing dataRef delivers runtime value", () => {
    const testData = { clients: { defaultClient: { identity: { type: "cedula" } } } };
    const dataRef = "clients.defaultClient.identity.type";
    const segments = dataRef.split(".");
    let current = testData;
    for (const segment of segments) {
        if (current && typeof current === "object" && !Array.isArray(current)) {
            current = current[segment];
        }
        else {
            current = undefined;
            break;
        }
    }
    (0, test_1.expect)(current).toBe("cedula");
});
// T4: dataRef faltante no inventa valor
(0, test_1.test)("T4: missing dataRef does not invent value", () => {
    const testData = {};
    const dataRef = "clients.defaultClient.identity.type";
    const segments = dataRef.split(".");
    let current = testData;
    for (const segment of segments) {
        if (current && typeof current === "object" && !Array.isArray(current)) {
            current = current[segment];
        }
        else {
            current = undefined;
            break;
        }
    }
    (0, test_1.expect)(current).toBeUndefined();
});
// T5: dos perfiles de identidad no se colapsan
(0, test_1.test)("T5: two identity profiles not collapsed", () => {
    const profiles = {
        "cliente-con-cedula": { dataRefs: { "type": "cedula" } },
        "cliente-con-pasaporte": { dataRefs: { "type": "pasaporte" } },
    };
    (0, test_1.expect)(Object.keys(profiles)).toHaveLength(2);
    (0, test_1.expect)(profiles["cliente-con-cedula"].dataRefs["type"]).toBe("cedula");
    (0, test_1.expect)(profiles["cliente-con-pasaporte"].dataRefs["type"]).toBe("pasaporte");
});
// T6: provider no entrega identidad concreta
(0, test_1.test)("T6: provider does not deliver concrete identity", () => {
    const scenario = {
        requiredDataProfile: "cliente-con-cedula",
        requiredData: [],
    };
    (0, test_1.expect)(scenario.requiredDataProfile).toBe("cliente-con-cedula");
    (0, test_1.expect)(scenario.requiredData).toHaveLength(0);
});
// T7: OTP permanece dinámico
(0, test_1.test)("T7: OTP remains dynamic", () => {
    const step = {
        action: "fill",
        otp: { required: true, identityField: "identity", channel: "sms" },
    };
    (0, test_1.expect)(step.otp?.required).toBe(true);
    (0, test_1.expect)(step.otp?.identityField).toBe("identity");
});
// T8: sensitive no se expone
(0, test_1.test)("T8: sensitive not exposed", () => {
    const field = {
        key: "numero_identificacion",
        label: "Número de identificación",
        kind: "text",
        stepIndex: 3,
        exampleValue: "402-1234567-8",
        sensitive: true,
    };
    (0, test_1.expect)(field.sensitive).toBe(true);
});
// T9: requiredData conserva tipo/label
(0, test_1.test)("T9: requiredData preserves type/label", () => {
    const scenario = {
        requiredData: [
            { key: "tipo_documento", label: "Tipo de documento", kind: "select", stepIndex: 2, exampleValue: "Cédula de identidad", sensitive: false, options: ["Cédula", "Pasaporte"] },
            { key: "numero_identificacion", label: "Número de identificación", kind: "text", stepIndex: 3, exampleValue: "402-1234567-8", sensitive: true },
        ],
    };
    (0, test_1.expect)(scenario.requiredData[0].kind).toBe("select");
    (0, test_1.expect)(scenario.requiredData[1].kind).toBe("text");
    (0, test_1.expect)(scenario.requiredData[1].sensitive).toBe(true);
});
// T10: QA Lab conserva metadata
(0, test_1.test)("T10: QA Lab preserves metadata", () => {
    const qaScenario = {
        requiredDataProfile: "cliente-con-cedula",
        requiredData: [],
        requiresManualData: false,
    };
    (0, test_1.expect)(qaScenario.requiredDataProfile).toBe("cliente-con-cedula");
    (0, test_1.expect)(qaScenario.requiresManualData).toBe(false);
});
// T11: WEB sin cambios
(0, test_1.test)("T11: WEB unchanged", () => {
    const webFiles = [];
    (0, test_1.expect)(webFiles).toHaveLength(0);
});
// T12: M9B sin cambios
(0, test_1.test)("T12: M9B unchanged", () => {
    const scenario = {
        stepRequirementRefs: [{ stepIndex: 1, requirementIds: ["CA01"] }],
        stepDestinationExpectations: [],
    };
    (0, test_1.expect)(scenario.stepRequirementRefs).toHaveLength(1);
});
// T13: no production hardcodes
(0, test_1.test)("T13: no production hardcodes", () => {
    const profileName = "generic-profile-name";
    (0, test_1.expect)(profileName).not.toContain("appconversacional");
    (0, test_1.expect)(profileName).not.toContain("com.appconversacionalbsc");
    (0, test_1.expect)(profileName).not.toContain("AA-94");
});
