import { Page, expect } from '@playwright/test';
import { waitForPromotedSpecStepReady, waitForListReadiness } from '../../../browser/promoted-spec-helpers';

// Page Object candidate: CategoryPage
// Generated by page-object-codegen
// Screen signature: screen:arquitectura-automatizacion-category
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37944-agregar-producto-al-carrito-desde-el-detalle-del-producto

export class CategoryPage {
  constructor(private readonly page: Page) {}

  async selectCategory(categoryName: string): Promise<void> {
    const previousUrl = this.page.url();
await this.page.getByRole('button', { name: categoryName }).or(this.page.getByRole('link', { name: categoryName })).click();
await waitForPromotedSpecStepReady(this.page, { previousUrl, expectEntityList: true });
  }
}
