import { Page, expect } from '@playwright/test';

// Page Object candidate: FormPage
// Generated by page-object-codegen
// Screen signature: screen:arquitectura-automatizacion-form
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37927-validar-inicio-de-sesion-con-credenciales-validas

export class FormPage {
  constructor(private readonly page: Page) {}

  async fillField(fieldName: string, value: string): Promise<void> {
    await this.page.getByLabel(fieldName).or(this.page.getByPlaceholder(fieldName)).fill(value);
  }

  async submit(): Promise<void> {
    await this.page.getByRole('button', { name: /submit|enviar|confirmar/i }).click();
  }
}
