import { Page, expect } from '@playwright/test';

// Page Object candidate: HomePage
// Generated by page-object-codegen
// Screen signature: screen:arquitectura-automatizacion-home
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37927-validar-inicio-de-sesion-con-credenciales-validas

export class HomePage {
  constructor(private readonly page: Page) {}

  async start(): Promise<void> {
    await this.page.goto('/');
await this.page.waitForLoadState('networkidle');
await this.page.waitForTimeout(1000);
const button = this.page.getByRole('button', { name: /iniciar sesión|iniciar|start|comenzar/i });
await button.waitFor({ state: 'visible', timeout: 10000 });
await button.click({ force: true });
await this.page.waitForLoadState('networkidle');
await this.page.waitForTimeout(3000);
  }

  async open(): Promise<void> {
    await this.page.goto('/');
  }

  async openLoginModal(): Promise<void> {
    const openLoginButton = this.page.getByRole('link', { name: /log in|iniciar sesion/i })
  .or(this.page.getByRole('button', { name: /log in|iniciar sesion/i }));
await openLoginButton.first().waitFor({ state: 'visible', timeout: 10000 });
await openLoginButton.first().click();
  }

  async openProductInformation(): Promise<void> {
    const previousUrl = this.page.url();
await this.page.getByRole('button', { name: /información de productos|product information/i }).click();
await waitForPromotedSpecStepReady(this.page, { previousUrl, expectEntityList: false });
  }
}
