import { Page, expect } from '@playwright/test';

// Page Object candidate: ProductDetailPage
// Generated by page-object-codegen
// Screen signature: screen:arquitectura-automatizacion-product_detail
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37870-generar-carta-de-referencia-con-certificado

export class ProductDetailPage {
  constructor(private readonly page: Page) {}

  async clickPrimaryAction(actionName: string): Promise<void> {
    const button = this.page.getByRole('button', { name: new RegExp(actionName, 'i') });
await button.waitFor({ state: 'visible', timeout: 10000 });
const isEnabled = await button.isEnabled({ timeout: 15000 }).catch(() => false);
if (!isEnabled) {
  const buttonText = await button.textContent().catch(() => '(unknown)');
  throw new Error('Cannot click primary action "' + actionName + '": button is not enabled. Text: "' + buttonText + '". This usually means required selections or form fields have not been completed.');
}
await button.click({ timeout: 10000 });
await this.page.waitForLoadState('domcontentloaded', { timeout: 10000 }).catch(() => {});
await this.page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
await this.page.waitForTimeout(1000);
  }
}
