"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.applyRegistryPromotion = exports.buildRegistryPromotionReport = exports.listSupportedActions = exports.getActionCapability = exports.actionRegistry = exports.registryLocatorToPlanTarget = exports.resolveRegistryObject = exports.normalizeRegistryText = exports.findRegistryObjectsByText = exports.validateObjectRegistry = exports.assertValidObjectRegistry = exports.saveObjectRegistry = exports.loadObjectRegistry = void 0;
var object_registry_loader_1 = require("./object-registry-loader");
Object.defineProperty(exports, "loadObjectRegistry", { enumerable: true, get: function () { return object_registry_loader_1.loadObjectRegistry; } });
Object.defineProperty(exports, "saveObjectRegistry", { enumerable: true, get: function () { return object_registry_loader_1.saveObjectRegistry; } });
var object_registry_validator_1 = require("./object-registry-validator");
Object.defineProperty(exports, "assertValidObjectRegistry", { enumerable: true, get: function () { return object_registry_validator_1.assertValidObjectRegistry; } });
Object.defineProperty(exports, "validateObjectRegistry", { enumerable: true, get: function () { return object_registry_validator_1.validateObjectRegistry; } });
var object_resolver_1 = require("./object-resolver");
Object.defineProperty(exports, "findRegistryObjectsByText", { enumerable: true, get: function () { return object_resolver_1.findRegistryObjectsByText; } });
Object.defineProperty(exports, "normalizeRegistryText", { enumerable: true, get: function () { return object_resolver_1.normalizeRegistryText; } });
Object.defineProperty(exports, "resolveRegistryObject", { enumerable: true, get: function () { return object_resolver_1.resolveRegistryObject; } });
var registry_target_adapter_1 = require("./registry-target-adapter");
Object.defineProperty(exports, "registryLocatorToPlanTarget", { enumerable: true, get: function () { return registry_target_adapter_1.registryLocatorToPlanTarget; } });
var action_registry_1 = require("./action-registry");
Object.defineProperty(exports, "actionRegistry", { enumerable: true, get: function () { return action_registry_1.actionRegistry; } });
Object.defineProperty(exports, "getActionCapability", { enumerable: true, get: function () { return action_registry_1.getActionCapability; } });
Object.defineProperty(exports, "listSupportedActions", { enumerable: true, get: function () { return action_registry_1.listSupportedActions; } });
var registry_promoter_1 = require("./registry-promoter");
Object.defineProperty(exports, "buildRegistryPromotionReport", { enumerable: true, get: function () { return registry_promoter_1.buildRegistryPromotionReport; } });
Object.defineProperty(exports, "applyRegistryPromotion", { enumerable: true, get: function () { return registry_promoter_1.applyRegistryPromotion; } });
