import { Page, expect } from '@playwright/test';

// Page Object candidate: HomePage
// Generated by page-object-codegen
// Screen signature: screen:default-home
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37844-visualizar-detalle-de-tarjeta-visa-gold

export class HomePage {
  constructor(private readonly page: Page) {}

  async start(): Promise<void> {
    await this.page.goto('/'); await this.page.getByRole('button', { name: /iniciar sesión|iniciar|start|comenzar/i }).click();
  }
}
