import { Page, expect } from '@playwright/test';
import { capturePageDiagnostics } from '../../../browser/promoted-spec-helpers';

// Page Object candidate: ProductDetailPage
// Generated by page-object-codegen
// Screen signature: screen:default-product_detail
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37869-generar-carta-de-referencia-con-cuenta-de-ahorro

export class ProductDetailPage {
  constructor(private readonly page: Page) {}

  async clickPrimaryAction(actionName: string): Promise<void> {
    const button = this.page.getByRole('button', { name: new RegExp(actionName, 'i') });

    await button.waitFor({ state: 'visible', timeout: 10000 });

    const isEnabled = await button.isEnabled({ timeout: 15000 }).catch(() => false);

    if (!isEnabled) {
      const diagnostics = await capturePageDiagnostics(this.page);
      const buttonText = await button.textContent().catch(() => '(unknown)');
      const buttonIsDisabled = await button.isDisabled().catch(() => false);

      const lines: string[] = [];
      lines.push(`Cannot click primary action "${actionName}": button is not enabled.`);
      lines.push(`  Button text: "${buttonText}"`);
      lines.push(`  Disabled: ${buttonIsDisabled}`);
      lines.push(`  Current URL: ${diagnostics.currentUrl}`);
      lines.push(`  Visible headings: [${diagnostics.visibleHeadings.map(h => `"${h}"`).join(', ')}]`);
      lines.push(`  List readiness: cards=${diagnostics.listReadiness.cardsVisible}, loading=${diagnostics.listReadiness.loadingDetected}`);
      lines.push(``);
      lines.push(`This usually means required selections or form fields have not been completed.`);
      lines.push(`Check that all product selections, category choices, or required inputs were applied before this action.`);

      throw new Error(lines.join('\n'));
    }

    await button.click({ timeout: 10000 });

    await this.page.waitForLoadState('domcontentloaded', { timeout: 10000 }).catch(() => {});
    await this.page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
    await this.page.waitForTimeout(1000);

    const loadingKeywords = ['cargando', 'loading', 'procesando', 'processing', 'espere', 'generando'];
    const maxWait = 15000;
    const pollMs = 500;
    const startTime = Date.now();
    while (Date.now() - startTime < maxWait) {
      const texts = await this.page.evaluate(() => {
        const texts: string[] = [];
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
        let node: Node | null;
        while ((node = walker.nextNode())) {
          const t = node.textContent?.trim();
          if (t) texts.push(t);
        }
        return texts;
      });
      const isStillLoading = texts.some(t => loadingKeywords.some(kw => t.toLowerCase().includes(kw)));
      if (!isStillLoading) break;
      await this.page.waitForTimeout(pollMs);
    }
  }

  async step4targetCduladeidentidaddominicanaderivedIntentclickprimaryactionexpectedOwnerProductDetailPageavailableMethodsMethod(): Promise<void> {
    // TODO: Implement step4targetCduladeidentidaddominicanaderivedIntentclickprimaryactionexpectedOwnerProductDetailPageavailableMethodsMethod with appropriate locators
    // intent: step=4 target="Cédula de identidad dominicana" derivedIntent="click_primary_action" expectedOwner="ProductDetailPage" availableMethods=[]
    // parameters: none
    throw new Error('Not implemented: step4targetCduladeidentidaddominicanaderivedIntentclickprimaryactionexpectedOwnerProductDetailPageavailableMethodsMethod');
  }

  async step5targetcontinuarderivedIntentclickprimaryactionexpectedOwnerProductDetailPageavailableMethodsMethod(): Promise<void> {
    // TODO: Implement step5targetcontinuarderivedIntentclickprimaryactionexpectedOwnerProductDetailPageavailableMethodsMethod with appropriate locators
    // intent: step=5 target="continuar" derivedIntent="click_primary_action" expectedOwner="ProductDetailPage" availableMethods=[]
    // parameters: none
    throw new Error('Not implemented: step5targetcontinuarderivedIntentclickprimaryactionexpectedOwnerProductDetailPageavailableMethodsMethod');
  }
}
