import { Page, expect } from '@playwright/test';
import { waitForPromotedSpecStepReady } from '../../../browser/promoted-spec-helpers';

// Page Object candidate: ProductInformationPage
// Generated by page-object-codegen
// Screen signature: screen:default-product_information
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37844-visualizar-detalle-de-tarjeta-visa-gold

export class ProductInformationPage {
  constructor(private readonly page: Page) {}

  async openProductInformation(): Promise<void> {
    const previousUrl = this.page.url();
    await this.page.getByRole('button', { name: /información de productos|product information/i }).click();
    await waitForPromotedSpecStepReady(this.page, { previousUrl, expectEntityList: false });
  }
}
