import { Page, expect } from '@playwright/test';

// Page Object candidate: ProductListPage
// Generated by page-object-codegen
// Screen signature: screen:default-product_list
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37844-visualizar-detalle-de-tarjeta-visa-gold

export class ProductListPage {
  constructor(private readonly page: Page) {}

  async selectProduct(productName: string): Promise<void> {
    const normalize = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
    const keywords = normalize(productName).split(/\s+/).filter(k => k.length > 2);
    const headings = this.page.locator('h1, h2, h3, h4, h5, h6');
    const count = await headings.count();
    for (let i = 0; i < count; i++) {
      const heading = headings.nth(i);
      const text = await heading.textContent();
      if (text) {
        const normalizedText = normalize(text);
        const matchCount = keywords.filter(k => normalizedText.includes(k)).length;
        if (matchCount >= Math.min(keywords.length - 1, 2)) {
          const card = heading.locator('xpath=ancestor::button|ancestor::a|ancestor::*[contains(@class, "card")][1]');
          await card.click();
          return;
        }
      }
    }
    await this.page.getByText(new RegExp(productName.split(/\s+/).join('|'), 'i')).first().click();
  }
}
