import { Page, expect } from '@playwright/test';

// Page Object candidate: LoginPage
// Generated by page-object-codegen
// Screen signature: screen:portalempresarial-login
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c44757-login-satisfactorio

export class LoginPage {
  constructor(private readonly page: Page) {}

  async fillUsername(value: string): Promise<void> {
    const usernameInput = this.page.locator('#logInModal').locator('#loginusername');
await usernameInput.waitFor({ state: 'visible', timeout: 10000 });
await usernameInput.fill(value);
  }

  async fillPassword(value: string): Promise<void> {
    const passwordInput = this.page.locator('#logInModal').locator('#loginpassword');
await passwordInput.waitFor({ state: 'visible', timeout: 10000 });
await passwordInput.fill(value);
  }
}
