import { Page, expect } from '@playwright/test';

// Page Object candidate: FormPage
// Generated by page-object-codegen
// Screen signature: screen:portal-comercial-form
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: preview-001-segunta-prueba

export class FormPage {
  constructor(private readonly page: Page) {}

  async fillField(fieldName: string, value: string): Promise<void> {
    await this.page.getByLabel(fieldName).or(this.page.getByPlaceholder(fieldName)).fill(value);
  }
}
