import { Page, expect } from '@playwright/test';

// Page Object candidate: LoginPage
// Generated by page-object-codegen
// Screen signature: screen:portal-comercial-login
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: preview-001-crear-producto-cuenta-efectivo

export class LoginPage {
  constructor(private readonly page: Page) {}

  async fillUsername(value: string): Promise<void> {
    const usernameInput = this.page.locator('#logInModal').locator('#loginusername');
await usernameInput.waitFor({ state: 'visible', timeout: 10000 });
await usernameInput.fill(value);
  }

  async fillPassword(value: string): Promise<void> {
    const passwordInput = this.page.locator('#logInModal').locator('#loginpassword');
await passwordInput.waitFor({ state: 'visible', timeout: 10000 });
await passwordInput.fill(value);
  }

  async submitLogin(): Promise<void> {
    const submitButton = this.page.locator('#logInModal').getByRole('button', { name: /log in|iniciar sesion/i });
await submitButton.first().waitFor({ state: 'visible', timeout: 10000 });
await submitButton.first().click();
  }
}
