import { Page, expect } from '@playwright/test';
import { waitForPromotedSpecStepReady, waitForListReadiness } from '../../../browser/promoted-spec-helpers';

// Page Object candidate: HomePage
// Generated by page-object-codegen
// Screen signature: screen:kiosko-home
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: preview-001-visualizar-categorias-principales-de-informacion-de-productos

export class HomePage {
  constructor(private readonly page: Page) {}

  async start(): Promise<void> {
    await this.page.goto('/');
await this.page.waitForLoadState('networkidle');
await this.page.waitForTimeout(1000);
const button = this.page.getByRole('button', { name: /iniciar sesión|iniciar|start|comenzar/i });
await button.waitFor({ state: 'visible', timeout: 10000 });
await button.click({ force: true });
await this.page.waitForLoadState('networkidle');
await this.page.waitForTimeout(3000);
  }
}
