import { Page, expect } from '@playwright/test';

// Page Object candidate: ProductDetailPage
// Generated by page-object-codegen
// Screen signature: screen:kiosko-product_detail
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: preview-005-regresar-al-listado-desde-el-detalle-del-producto

export class ProductDetailPage {
  constructor(private readonly page: Page) {}

  async expectLoaded(): Promise<void> {
    await expect(this.page.locator('body')).toBeVisible();
  }
}
