import { Page, expect } from '@playwright/test';
import { waitForPromotedSpecStepReady, waitForListReadiness } from '../../../browser/promoted-spec-helpers';

// Page Object candidate: ProductListPage
// Generated by page-object-codegen
// Screen signature: screen:kiosko-product_list
// Status: candidate
// Confidence: 0.5
//
// REVIEW REQUIRED: This is a candidate Page Object.
// - Verify locators are correct for your application.
// - Rename methods if needed.
// - Do not activate until reviewed.
//
// Source plans: c37844-visualizar-detalle-de-tarjeta-visa-gold

export class ProductListPage {
  constructor(private readonly page: Page) {}

  async selectProduct(productName: string): Promise<void> {
    await waitForListReadiness(this.page, { timeoutMs: 10000, pollMs: 500, minCards: 1 });
const normalize = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
const target = normalize(productName);
const allTokens = target.split(/\s+/).filter(t => t.length > 2);
const stopWords = new Set(['de','del','la','el','los','las','un','una','con','sin','por','para','the','a','an','in','on','at','to','for']);
const strongTokens = allTokens.filter(t => !stopWords.has(t));
const tokensToMatch = strongTokens.length > 0 ? strongTokens : allTokens;
if (tokensToMatch.length === 0) throw new Error('Product target "' + productName + '" has no meaningful tokens.');
const checkboxRegex = new RegExp(tokensToMatch.map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('.*'), 'i');
const checkbox = this.page.getByRole('checkbox', { name: checkboxRegex, exact: false });
if (await checkbox.count() > 0) {
  const isChecked = await checkbox.first().isChecked().catch(() => false);
  if (!isChecked) { await checkbox.first().click({ timeout: 10000 }); }
  return;
}
const roleRegex = new RegExp(tokensToMatch.map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('.*'), 'i');
const rolesToTry = ['button', 'link', 'option', 'radio', 'menuitem'];
for (const role of rolesToTry) {
  const locator = this.page.getByRole(role as any, { name: roleRegex, exact: false });
  if (await locator.count() > 0) { await locator.first().click({ timeout: 10000 }); return; }
}
const headingRegex = new RegExp(tokensToMatch.map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('.*'), 'i');
const headingLocator = this.page.locator('h1, h2, h3, h4, h5, h6').filter({ hasText: headingRegex }).first();
try {
  if (await headingLocator.count() > 0) {
    const headingHandle = await headingLocator.elementHandle({ timeout: 5000 });
    if (headingHandle) {
      const ancestor = await headingHandle.evaluateHandle((el) => {
        let current = el as HTMLElement; let depth = 0;
        const clickableTags = ['button', 'a', 'input', 'label'];
        const clickableRoles = ['button', 'link', 'option', 'radio', 'checkbox', 'tab', 'menuitem'];
        const clickableClassPatterns = ['card', 'cursor-pointer', 'clickable', 'btn', 'interactive', 'selectable'];
        while (current && depth < 5) {
          const tagName = current.tagName.toLowerCase();
          const role = current.getAttribute('role');
          const hasOnClick = !!(current as any).onclick || current.getAttribute('onclick');
          const hasClickableClass = clickableClassPatterns.some(p => typeof current.className === 'string' && current.className.includes(p));
          if (clickableTags.includes(tagName) || clickableRoles.includes(role || '') || hasOnClick || hasClickableClass) return current;
          current = current.parentElement; depth++;
        }
        return null;
      });
      const ancestorElement = ancestor.asElement();
      if (ancestorElement) { await ancestorElement.click({ timeout: 10000 }); return; }
      await headingLocator.click({ timeout: 10000 }); return;
    }
  }
} catch { /* continue */ }
const fallbackLocator = this.page.locator(':has-text("' + productName.replace(/"/g, '\\"') + '")').first();
if (await fallbackLocator.count() > 0) { await fallbackLocator.click({ timeout: 10000 }); return; }
throw new Error('Could not find product matching "' + productName + '". Strategies tried: checkbox, role, text, heading, semantic_tokens, product_condition');
  }
}
