export type AutoGeneratedDataType =
  | "person_name"
  | "first_name"
  | "last_name"
  | "country"
  | "city"
  | "address"
  | "email"
  | "phone"
  | "numeric"
  | "amount"
  | "month"
  | "year"
  | "date"
  | "description"
  | "search_term"
  | "company_name"
  | "tax_id"
  | "credit_card_test_number"
  | "cvv_test"
  | "password"
  | "otp";

export type AutoGenerateConfig = {
  enabled: boolean;
  generateSensitiveData: boolean;
  profile: "demo" | "qa" | "staging" | "production_like";
};

export type AutoGeneratedDataResult = {
  generated: boolean;
  value?: string;
  type?: AutoGeneratedDataType;
  sensitive?: boolean;
  demoSafe?: boolean;
  reason?: string;
};

const DEFAULT_CONFIG: AutoGenerateConfig = {
  enabled: false,
  generateSensitiveData: false,
  profile: "qa"
};

const TEST_CREDIT_CARDS: Record<string, string> = {
  visa: "4111111111111111",
  mastercard: "5500000000000004",
  amex: "340000000000009",
  discover: "6011000000000004"
};

const TEST_COUNTRIES = ["United States", "Canada", "United Kingdom", "Australia", "Germany", "France", "Spain", "Mexico", "Brazil", "Argentina"];
const TEST_CITIES = ["New York", "Los Angeles", "Chicago", "Toronto", "London", "Berlin", "Paris", "Madrid", "Mexico City", "São Paulo"];
const TEST_FIRST_NAMES = ["John", "Jane", "Carlos", "María", "Michael", "Sarah", "David", "Laura", "Robert", "Anna"];
const TEST_LAST_NAMES = ["Smith", "Johnson", "García", "Martínez", "Williams", "Brown", "Jones", "Miller", "Davis", "Wilson"];
const TEST_COMPANIES = ["Acme Corp", "Tech Solutions", "Global Industries", "Innovation Labs", "Digital Services", "Cloud Systems"];

function getRandomItem<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generatePersonName(): string {
  return `${getRandomItem(TEST_FIRST_NAMES)} ${getRandomItem(TEST_LAST_NAMES)}`;
}

function generateFirstName(): string {
  return getRandomItem(TEST_FIRST_NAMES);
}

function generateLastName(): string {
  return getRandomItem(TEST_LAST_NAMES);
}

function generateCountry(): string {
  return getRandomItem(TEST_COUNTRIES);
}

function generateCity(): string {
  return getRandomItem(TEST_CITIES);
}

function generateAddress(): string {
  const num = Math.floor(Math.random() * 9000) + 100;
  const street = getRandomItem(["Main St", "Oak Ave", "Maple Rd", "Park Blvd", "Center St"]);
  return `${num} ${street}`;
}

function generateEmail(): string {
  const name = generateFirstName().toLowerCase();
  const domain = getRandomItem(["example.com", "test.com", "demo.com", "mail.com"]);
  return `${name}${Math.floor(Math.random() * 1000)}@${domain}`;
}

function generatePhone(): string {
  const area = Math.floor(Math.random() * 800) + 200;
  const prefix = Math.floor(Math.random() * 800) + 200;
  const line = Math.floor(Math.random() * 9000) + 1000;
  return `(${area}) ${prefix}-${line}`;
}

function generateNumeric(): string {
  return String(Math.floor(Math.random() * 9000) + 1000);
}

function generateAmount(): string {
  return (Math.random() * 900 + 10).toFixed(2);
}

function generateMonth(): string {
  return String(Math.floor(Math.random() * 12) + 1).padStart(2, "0");
}

function generateYear(): string {
  const currentYear = new Date().getFullYear();
  return String(currentYear + Math.floor(Math.random() * 5) + 1);
}

function generateDate(): string {
  const year = generateYear();
  const month = generateMonth();
  const day = String(Math.floor(Math.random() * 28) + 1).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function generateDescription(): string {
  return "Test description for automated testing purposes";
}

function generateSearchTerm(): string {
  return getRandomItem(["Product", "Item", "Service", "Test", "Demo"]);
}

function generateCompanyName(): string {
  return getRandomItem(TEST_COMPANIES);
}

function generateTaxId(profile: string): string | null {
  if (profile === "production_like") {
    return null;
  }
  return `TEST-${Math.floor(Math.random() * 900000) + 100000}`;
}

function generateCreditCardTestNumber(): string | null {
  return getRandomItem(Object.values(TEST_CREDIT_CARDS));
}

function generateCvvTest(): string {
  return String(Math.floor(Math.random() * 900) + 100);
}

function detectDataType(key: string, field?: string, context?: string): AutoGeneratedDataType | null {
  const normalized = `${key} ${field || ""} ${context || ""}`.toLowerCase();
  
  if (normalized.includes("nombre") || normalized.includes("name") || normalized.includes("fullname")) {
    if (normalized.includes("first") || normalized.includes("nombre")) return "first_name";
    if (normalized.includes("last") || normalized.includes("apellido")) return "last_name";
    return "person_name";
  }
  
  if (normalized.includes("pais") || normalized.includes("country")) return "country";
  if (normalized.includes("ciudad") || normalized.includes("city")) return "city";
  if (normalized.includes("direccion") || normalized.includes("address")) return "address";
  if (normalized.includes("correo") || normalized.includes("email")) return "email";
  if (normalized.includes("telefono") || normalized.includes("phone") || normalized.includes("celular")) return "phone";
  if (normalized.includes("monto") || normalized.includes("amount") || normalized.includes("importe")) return "amount";
  if (normalized.includes("mes") || normalized.includes("month")) return "month";
  if (normalized.includes("año") || normalized.includes("anio") || normalized.includes("year")) return "year";
  if (normalized.includes("fecha") || normalized.includes("date")) return "date";
  if (normalized.includes("descripcion") || normalized.includes("description") || normalized.includes("comentario")) return "description";
  if (normalized.includes("busqueda") || normalized.includes("search")) return "search_term";
  if (normalized.includes("empresa") || normalized.includes("company")) return "company_name";
  if (normalized.includes("tax") || normalized.includes("impuesto") || normalized.includes("rfc") || normalized.includes("nit")) return "tax_id";
  if (normalized.includes("tarjeta") || normalized.includes("card") || normalized.includes("credit")) return "credit_card_test_number";
  if (normalized.includes("cvv") || normalized.includes("cvc")) return "cvv_test";
  if (normalized.includes("numerico") || normalized.includes("numeric") || normalized.includes("number")) return "numeric";
  
  return null;
}

function isSensitiveType(type: AutoGeneratedDataType): boolean {
  return ["credit_card_test_number", "cvv_test", "password", "otp", "tax_id"].includes(type);
}

function isDemoSafeType(type: AutoGeneratedDataType): boolean {
  return ["credit_card_test_number", "cvv_test", "tax_id"].includes(type);
}

function isFinancialContext(context?: string): boolean {
  if (!context) return false;
  const normalized = context.toLowerCase();
  return normalized.includes("transfer") || 
         normalized.includes("payment") || 
         normalized.includes("pago") || 
         normalized.includes("compra") || 
         normalized.includes("purchase") ||
         normalized.includes("loan") ||
         normalized.includes("prestamo");
}

function maskSensitiveValue(value: string, type: AutoGeneratedDataType): string {
  if (type === "credit_card_test_number") {
    return `************${value.slice(-4)}`;
  }
  if (type === "cvv_test") {
    return "***";
  }
  if (type === "tax_id") {
    return `***${value.slice(-4)}`;
  }
  return "***";
}

export function autoGenerateTestData(
  key: string,
  field?: string,
  context?: string,
  config: AutoGenerateConfig = DEFAULT_CONFIG
): AutoGeneratedDataResult {
  if (!config.enabled) {
    return { generated: false, reason: "auto_generate_test_data_disabled" };
  }
  
  const dataType = detectDataType(key, field, context);
  
  if (!dataType) {
    return { generated: false, reason: "unknown_data_type" };
  }
  
  const isSensitive = isSensitiveType(dataType);
  const isDemoSafe = isDemoSafeType(dataType);
  const isDemoProfile = config.profile === "demo";
  
  if (isSensitive) {
    if (isDemoSafe && isDemoProfile) {
      console.log(`[auto-test-data] Demo-safe sensitive type "${dataType}" allowed for demo profile`);
    } else if (!config.generateSensitiveData) {
      return { 
        generated: false, 
        type: dataType, 
        sensitive: true, 
        reason: "sensitive_data_generation_disabled" 
      };
    }
    
    if (config.profile === "production_like" && ["tax_id", "credit_card_test_number", "cvv_test"].includes(dataType)) {
      return {
        generated: false,
        type: dataType,
        sensitive: true,
        reason: "production_profile_restricts_sensitive_data"
      };
    }
  }
  
  if (isFinancialContext(context) && ["amount", "credit_card_test_number"].includes(dataType)) {
    if (!config.generateSensitiveData && !isDemoProfile) {
      return {
        generated: false,
        type: dataType,
        sensitive: true,
        reason: "financial_data_requires_sensitive_enabled_or_demo"
      };
    }
  }
  
  let value: string | null = null;
  
  switch (dataType) {
    case "person_name":
      value = generatePersonName();
      break;
    case "first_name":
      value = generateFirstName();
      break;
    case "last_name":
      value = generateLastName();
      break;
    case "country":
      value = generateCountry();
      break;
    case "city":
      value = generateCity();
      break;
    case "address":
      value = generateAddress();
      break;
    case "email":
      value = generateEmail();
      break;
    case "phone":
      value = generatePhone();
      break;
    case "numeric":
      value = generateNumeric();
      break;
    case "amount":
      value = generateAmount();
      break;
    case "month":
      value = generateMonth();
      break;
    case "year":
      value = generateYear();
      break;
    case "date":
      value = generateDate();
      break;
    case "description":
      value = generateDescription();
      break;
    case "search_term":
      value = generateSearchTerm();
      break;
    case "company_name":
      value = generateCompanyName();
      break;
    case "tax_id":
      value = generateTaxId(config.profile);
      break;
    case "credit_card_test_number":
      value = generateCreditCardTestNumber();
      break;
    case "cvv_test":
      value = generateCvvTest();
      break;
    case "password":
    case "otp":
      return {
        generated: false,
        type: dataType,
        sensitive: true,
        reason: "password_and_otp_cannot_be_auto_generated"
      };
  }
  
  if (value === null) {
    return {
      generated: false,
      type: dataType,
      sensitive: isSensitive,
      reason: "generation_not_supported_for_profile"
    };
  }
  
  const maskedValue = isSensitive ? maskSensitiveValue(value, dataType) : undefined;
  if (maskedValue) {
    console.log(`[auto-test-data] Generated sensitive value: type="${dataType}" masked="${maskedValue}" profile="${config.profile}" demoSafe=${isDemoSafe && isDemoProfile}`);
  }
  
  return {
    generated: true,
    value,
    type: dataType,
    sensitive: isSensitive,
    demoSafe: isDemoSafe && isDemoProfile
  };
}

export { detectDataType, isSensitiveType };
