import type { MissingInputBehavior, TestDataAliasesMap } from "../types/env.types";
import { autoGenerateTestData, type AutoGenerateConfig, type AutoGeneratedDataResult } from "./auto-test-data-generator";

export type DataKeyResolution = {
  status: "resolved" | "missing" | "skipped" | "auto_generated" | "missing_sensitive";
  key: string;
  value?: string;
  source?: string;
  masked?: boolean;
  error?: string;
  autoGenerated?: boolean;
  generatedType?: string;
};

const SENSITIVE_KEYS = ["password", "contrasena", "contraseña", "clave", "pin", "token", "otp", "secret"];

function isSensitiveKey(key: string): boolean {
  const normalized = key.toLowerCase();
  return SENSITIVE_KEYS.some(s => normalized.includes(s));
}

function maskValue(value: string): string {
  if (value.length <= 4) return "***";
  return "***" + value.slice(-3);
}

function normalizeKey(key: string): string {
  return key
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9_]/g, "_")
    .trim();
}

export function resolveDataKey(
  key: string,
  options: {
    testData?: Record<string, unknown>;
    testDataAliases?: TestDataAliasesMap;
    env?: Record<string, string | undefined>;
    missingInputBehavior?: MissingInputBehavior;
    autoGenerateConfig?: AutoGenerateConfig;
    field?: string;
    context?: string;
  }
): DataKeyResolution {
  const { testData, testDataAliases, env = {}, missingInputBehavior = "fail", autoGenerateConfig, field, context } = options;
  const normalizedKey = normalizeKey(key);
  
  // Priority 1: Direct lookup in APP_TEST_DATA_JSON
  if (testData && key in testData) {
    const value = testData[key];
    if (value !== undefined && value !== null) {
      return {
        status: "resolved",
        key,
        value: String(value),
        source: "APP_TEST_DATA_JSON",
        masked: isSensitiveKey(key)
      };
    }
  }
  
  // Priority 2: Resolve through aliases
  if (testDataAliases && key in testDataAliases) {
    const aliases = testDataAliases[key];
    const aliasList = Array.isArray(aliases) ? aliases : [aliases];
    
    for (const alias of aliasList) {
      if (testData && alias in testData) {
        const value = testData[alias];
        if (value !== undefined && value !== null) {
          return {
            status: "resolved",
            key,
            value: String(value),
            source: `APP_TEST_DATA_JSON (alias: ${alias})`,
            masked: isSensitiveKey(key)
          };
        }
      }
    }
  }
  
  // Priority 3: Standard credential mappings
  const credentialMappings: Record<string, string[]> = {
    "usuario_valido": ["APP_USERNAME", "APP_USERNAME"],
    "username_valido": ["APP_USERNAME", "APP_USERNAME"],
    "user_valido": ["APP_USERNAME", "APP_USERNAME"],
    "contrasena_valida": ["APP_PASSWORD", "APP_PASSWORD"],
    "contraseña_valida": ["APP_PASSWORD", "APP_PASSWORD"],
    "password_valido": ["APP_PASSWORD", "APP_PASSWORD"],
    "clave_valida": ["APP_PASSWORD", "APP_PASSWORD"]
  };
  
  for (const [pattern, envVars] of Object.entries(credentialMappings)) {
    if (normalizeKey(key) === normalizeKey(pattern)) {
      for (const envVar of envVars) {
        const value = env[envVar];
        if (value) {
          return {
            status: "resolved",
            key,
            value,
            source: envVar,
            masked: true
          };
        }
      }
    }
  }
  
  // Priority 4: Direct env var lookup by normalized key
  const possibleEnvVars = [
    `APP_${normalizedKey.toUpperCase()}`,
    normalizedKey.toUpperCase(),
    key.toUpperCase()
  ];
  
  for (const envVar of possibleEnvVars) {
    const value = env[envVar];
    if (value) {
      return {
        status: "resolved",
        key,
        value,
        source: envVar,
        masked: isSensitiveKey(key)
      };
    }
  }
  
  // Priority 5: Auto-generate if enabled and data is missing
  if (autoGenerateConfig?.enabled && missingInputBehavior === "auto_generate") {
    const autoResult = autoGenerateTestData(key, field, context, autoGenerateConfig);
    
    if (autoResult.generated && autoResult.value) {
      return {
        status: "auto_generated",
        key,
        value: autoResult.value,
        source: "auto_generated",
        masked: autoResult.sensitive,
        autoGenerated: true,
        generatedType: autoResult.type
      };
    }
    
    if (autoResult.sensitive && !autoResult.generated) {
      return {
        status: "missing_sensitive",
        key,
        error: `Sensitive data key "${key}" cannot be auto-generated. Reason: ${autoResult.reason || "policy_restriction"}`,
        masked: true
      };
    }
  }
  
  // Priority 6: Handle missing based on behavior
  if (missingInputBehavior === "skip") {
    return {
      status: "skipped",
      key,
      error: `Data key "${key}" not found, skipped due to missingInputBehavior=skip`
    };
  }
  
  // Check if this is a sensitive key that's missing
  if (isSensitiveKey(key)) {
    return {
      status: "missing_sensitive",
      key,
      error: `Missing sensitive test data value for key "${key}". Set APP_TEST_DATA_JSON.${key} or APP_${key.toUpperCase()}`
    };
  }
  
  return {
    status: "missing",
    key,
    error: `Missing test data value for key "${key}". Set APP_TEST_DATA_JSON.${key} or APP_${key.toUpperCase()}`
  };
}

export function formatDataKeyForLog(resolution: DataKeyResolution): string {
  if (resolution.status !== "resolved" && resolution.status !== "auto_generated") {
    return `[data-resolver] key="${resolution.key}" status="${resolution.status}" ${resolution.error ? `error="${resolution.error}"` : ""}`;
  }
  
  const valueDisplay = resolution.masked ? maskValue(resolution.value!) : resolution.value;
  const sourceInfo = resolution.autoGenerated 
    ? `source="${resolution.source}" type="${resolution.generatedType || "unknown"}"`
    : `source="${resolution.source}"`;
  return `[data-resolver] key="${resolution.key}" ${sourceInfo} value="${valueDisplay}"`;
}
